adopted-ember-addons/ember-data-factory-guy

README.md

Doc changes for https://github.com/danielspaniel/ember-data-factory-guy/pull/47

Updating docs for DS.FixtureAdapter

---

src/factory_guy_test_mixin.js

Allows one to subclass / reopen FactoryGuyTestMixin and configures a custom object mapping.
For example, Django Tastypie returns:
```
objects: [ { }, { }, ... ]
meta: { ... }
```
FactoryGuyTestMixin only returns:
```
clients: [ ... ]
```

Allows custom mapping of objects.

---

src/mock_create_request.js

When I use `FactoryGuyTestMixin#handleCreate` without a match, it correctly mocks my POST request. When I use a match, it creates a record in my app's store from the match data. Thus my assertion that there should be one record fails, as there are two.
I'm not sure if this is the correct approach, but immediately deleting the record after serialization solves the problem for me. Here's my test case. MODEL is the factory fixture name and helper is a FactoryGuyTestMixin.
```javascript
test('Create', function () {
expect(2);
visit('/');
andThen(function () {
equal(find('#main table tbody tr').length, 0, 'There should be no todos');
fillIn('#new-todo', 'Item 1');
// after this, there is one record
// helper.handleCreate(MODEL);
// after this, there are two records
helper.handleCreate(MODEL, …
```

Delete records created by MockCreateRequest

---

src/factory_guy.js
src/model_definition.js
tests/factory_guy_test.js

When building a fixture with relationships, FactoryGuy.build() is called with the relationship attribute name rather than that attributes model type.
It currently works only when relationship attributes have the same name as the model type they're related to.
So this works:
User = DS.Model.extend({
company:     DS.belongsTo('company',)
});
But this doesn't:
User = DS.Model.extend({
default_company:     DS.belongsTo('company',)
});
Build tries to find a factory named 'default_company' rather than the 'company' factory.

Use  typeKey for relationship instead of attribute name for build fixture relationship

---

addon/factory-guy-test-helper.js
addon/factory-guy.js
tests/dummy/app/components/translate.js
tests/dummy/app/models/user.js
tests/dummy/config/environment.js
tests/unit/rest-adapter-factory-test.js

The app I'm working on requires that I [disable prototype extensions](http://guides.emberjs.com/v1.10.0/configuring-ember/disabling-prototype-extensions/). Factory Guy wasn't coded to accommodate that.
This commit at least gets the tests passing after I changed `tests/dummy/config/environment.js` so that `EXTEND_PROTOTYPES` is `false`. I'm not sure that it fixes all of the issues that may be introduced, but at least it's letting me test my app now.
The [new default](https://github.com/ember-cli/ember-cli/issues/3443) for developing add-ons is to have prototype extensions turned off, so this brings Factory Guy up to code with that standard.

Get this add-on working when prototype extensions are disabled in Ember

---

addon/factory-guy-test-helper.js
addon/mock-get-request.js
tests/unit/factory-guy-test-helper-test.js

This pullrequest implements issue #84 it adds the same `andFail()` method chaining functionality that is already implemented for `PUT` and `DELETE` requests to the `handleFind()` test-helper.
TODO:

[WIP] Add andFail() method to handleFind()

---

addon/factory-guy-test-helper.js
addon/factory-guy.js
app/initializers/ember-data-factory-guy.js
vendor/assets/javascripts/ember_data_factory_guy.js

fixs
```
DEPRECATION: You tried to look up 'store:main', but this has been deprecated in favor of 'store:application'.
at ember$data$lib$system$container$proxy$$ContainerProxy.registerDeprecation.preLookupCallback (http://localhost:4200/provider/assets/vendor.js:125945:15)
at Object.ember$data$lib$system$container$proxy$$ContainerProxy.aliasedFactory.create (http://localhost:4200/provider/assets/vendor.js:125929:13)
at instantiate (http://localhost:4200/provider/assets/vendor.js:17010:26)
at lookup (http://localhost:4200/provider/assets/vendor.js:16849:19)
at Object.Container.lookup (http://localhost:4200/provider/assets/vendor.js:16494:16)
at exports.default.initialize (http://localhost:4200/provider/assets/inbox-dashboard.js:7014:48)
at …
```

update store:main references to use store:application as store:main is now deprecated

---

addon/factory-guy.js

Ember addons are expected to work without prototype extensions, because an application may or may not have prototype extensions enabled, and addons need to work with any application. (Plus, my application has them disabled, and Factory Guy broke.)

Work without prototype extensions

---

addon/factory-guy.js
app/initializers/ember-data-factory-guy.js
package.json

* Fix error due to removal of DS.ActiveModelAdapter
* Fix error due to container.lookup being undefined in initializer

Ember 2.0 fixes

---

addon/jsonapi-attribute-transformer.js

This should resolve issue #116, but it's just an initial set of commits.
However, if I'm going in the completely wrong direction, anyone is free to point it out.
At this point, It seems the fix works with our project, but it's not covered with tests yet. I haven't quite figured out the tests yet and I don't want to upset the established conventions.
The way I see it, I should
* Have two models which use two serializers, both of which use something other than the default dasherize approach for serializing attribute and relationship keys. Underscore is probably easiest.
* Check that making/building fixtures using those models and their factories gives me models with proper keys and relationships present.
Anything I may have missed?
An unfortunate consequence of the approach I used is that I …

Allow usage of applications serializer to transform attributes

---

index.js

This PR resolves the issue described in #124 
If the described issue is in fact not an issue, feel free to ignore and close it.

Changed how to determine if mockjax should be loaded

---

addon/rest-fixture-converter.js
tests/dummy/app/models/profile.js
tests/dummy/app/tests/factories/profile.js
tests/unit/active-model-adapter-test.js
tests/unit/jsonapi-adapter-test.js
tests/unit/rest-adapter-test.js

@danielspaniel I encountered a potential bug in factory guy - If a definition or a build (with custom attribute) contains an attribute with a default value that is `false`, that attribute does not get carried over into the store or get converted properly. 
```javascript
// addon/rest-fixture-converter.js
var extractAttributes = function (modelName, fixture) {
var attributes = {};
var transformFunction = getTransformFunction(modelName, 'Attribute');
store.modelFor(modelName).eachAttribute(function (attribute) {
var attributeKey = transformFunction(attribute);
//console.log('attribute', attribute, attributeKey, fixture.hasOwnProperty(attribute), fixture.hasOwnProperty(attributeKey))
if (fixture[attribute]) {
attributes[attributeKey] = fixture[attribute];
} else if (fixture[attributeKey]) { …
```

Attribute typing

---

blueprints/ember-data-factory-guy/index.js
index.js

I am using ember-cli@1.13.8, `jquery-mockjax` didn't added automatically to my bower.json after installing ember-data-factory-guy, I had to remove initialize function from `blueprints/ember-data-factory-guy/index.js` to make it work.
I also removed `blueprintsPath` from `index.js` because this is only required when `blueprints` is not present in root directory. http://www.ember-cli.com/extending/#blueprint-conventions

Fix jquery-mockjax bower package addition to Project

---

addon/factory-guy-test-helper.js
addon/factory-guy.js

Continuing the work initiated in 7cf90b1c3c7a130298675386fe13edd50477ed78, this PR removes the last occurrences of `FactoryGuy.getStore()`.

Removes legacy getStore method

---

README.md
addon/factory-guy-test-helper.js
addon/factory-guy.js
addon/fixture-builder-factory.js
addon/fixture-builder.js
addon/jsonapi-fixture-builder.js
addon/mock-update-request.js
addon/rest-fixture-builder.js
tests/unit/factory-guy-test.js

In order to be compatible with custom formatters, removing `FactoryGuy.useJSONAPI()` was necessary, mostly because there was no way to tell FactoryGuy how to fetch IDs (see https://github.com/danielspaniel/ember-data-factory-guy/compare/master...xcambar:no_more_useJSONAPI?expand=1#diff-163b229985a285775137075bd760cff9L123).
`useJSONAPI` was used for 3 reasons:
1. extract the IDs from a payload (see above)
1. determine which HTTP verb to use for updates
1. wraps the payload (for RESTSerializer)
The responsibility for these has been transfered to the Builder, which are now the only objects aware (and needing to be aware) of the expected format.
Hope you'll like it!

No more useJSONAPI

---

README.md
addon/factory-guy.js
tests/unit/factory-guy-test.js
tests/unit/shared-factory-guy-test-helper-tests.js

The `handleFindAll` function is a bit lacking in that all of the models it generates are identical (except for sequences).  This PR allows it to be called with a list of traits/options instead of a number.
```javascript
// findAll('user') will return Alice, Bob, and Charlotte (who is an admin)
TestHelper.handleFindAll('user', {name: 'Alice'}, {name: 'Bob'}, ['admin', {name: 'Charlotte'}]);
```

handleFindAll() and buildList() can make diverse models

---

addon/factory-guy-test-helper.js
addon/mock-create-request.js
addon/mock-update-request.js
tests/unit/shared-factory-guy-test-helper-tests.js

A small one, I saw your comment [here](https://github.com/danielspaniel/ember-data-factory-guy/compare/master...xcambar:deprecates_options_succeed?expand=1#diff-9872310e9a623729710540206c140e36R59) about supporting old non-chaining methods and thought that could be good to use `Ember.deprecate` to help developers migrate, or at least show them that it is deprecated.
FYI, I indicated version `3.0.0` as the limit of availability because it will be a breaking change, and I simply followed SemVer here.

Deprecates options succeed

---

addon/mock-query-request.js
tests/unit/shared-factory-guy-test-helper-tests.js

Hi,
Migrating from 1.13.10 to 2.1.3 I noticed that handleQuery no longer works for nested query parameters
TestHelper.handleQuery('foo', { a: { b: 'c' } })
...
this.store.query('foo', { a: { b: 'c' } })
from https://github.com/danielspaniel/ember-data-factory-guy/commit/fcce319a96262cbfbd63ad9b28d73e60d977436f I'd say it's not on purpose.
This adds support for this case that is not so uncommon.

Supporting nested query params comparisons in handleQuery

---

addon/jsonapi-attribute-transformer.js
addon/rest-fixture-converter.js
tests/unit/active-model-adapter-test.js
tests/unit/jsonapi-adapter-test.js

Ember-Data models can have attributes defined with a custom type, which [applies a transform](https://guides.emberjs.com/v2.0.0/models/defining-models/#toc_transforms) when the attribute is serialized or deserialized.
For now, Ember-Data-Factory-Guy's `make()` already support these kind of custom attributes. But `build()` just ignores the transform, and puts the raw attribute value in the generated payload.
This MR makes `RESTFixtureConverter` and `JSONAPIFixtureConverter` aware of transformed attributes.
```c
// model/user.js
export DS.Model.extend({
info: attr('object'),
});
// transform/object.js
export DS.Transform.extend({
serialize: function(deserialized) {
return deserialized ? JSON.stringify(deserialized) : "{}"
}
});
// Tests
build('user', {info: {first: 1}} );
var expectedJson = …
```

build(): apply transform of custom type when serializing attributes

---

addon/jsonapi-fixture-converter.js
tests/unit/shared-factory-guy-tests.js

Handle FactoryGuy.make() with relationships specified as IDs.

Return fixture relationship IDs if not an object (fix #166)

---

addon/converter/fixture-converter.js
tests/dummy/app/models/profile.js
tests/dummy/app/serializers/profile.js
tests/dummy/app/transforms/just-a-string.js
tests/unit/models/profile-test.js

This adds a workaround for compatibility with ember-data-model-fragments, as discussed in #182.
@patocallaghan you mentioned that the workaround did not work for you before, could you try this branch when you have the time? (you'll need to use `"ember-data-factory-guy": "whatthewhat/ember-data-factory-guy#model-fragments-compatibility"` in your package.json)
I only tested it on 1 app, but it seems to be working ok with ember-data-model-fragments 1.13.1 and ember-data 1.13.16
Closes #182

Fix compatibility with ember-data-model-fragments

---

addon/mocks/mock-create-request.js
tests/unit/shared-factory-guy-test-helper-tests.js

convert the root key from `my-model-name` to `my_model_name` so that we access the data properly.
See issue https://github.com/danielspaniel/ember-data-factory-guy/issues/165 for more detail

Handle active model formatted request data properly

---

addon/factory-guy.js
addon/mocks/mock-get-request.js
addon/payload/rest-payload.js

Wrap arrays that use prototype extensions in Ember.A()

---

addon/utils/helper-functions.js
tests/unit/utils/helper-functions-test.js

Currently, array parameters do not work for `mockQuery` because this tests strict equivalence versus the contents of the array.
This PR addresses the issue by breaking the `isEquivalent` function into three pieces and then makes use of recursion to deal with nested equality.
The three pieces are: 
1. Object Equivalence - slightly modified take on your algorithm 
2. Array Equivalence - contents and order of `arrayA` are identical to contents and order of `arrayB`
3. Normal Strict Equivalence `===` 
I would like some feedback on how you would like me to test the array case, since `user-search-test` is using `fillIn` and we need an array and an object as a param.

refactor the equivalence function so that it works with arrays as well

---

package.json
tests/acceptance/employee-view-test.js
tests/dummy/app/components/single-employee.js
tests/dummy/app/models/billing-address.js
tests/dummy/app/models/department-employment.js
tests/dummy/app/models/department.js
tests/dummy/app/models/employee.js
tests/dummy/app/models/mailing-address.js
tests/dummy/app/models/name.js
tests/dummy/app/models/nested-fragment/address.js
tests/dummy/app/router.js
tests/dummy/app/routes/employees.js
tests/dummy/app/templates/components/single-employee.hbs
tests/dummy/app/templates/employee.hbs
tests/dummy/app/templates/employees.js
tests/dummy/app/tests/factories/address.js
tests/dummy/app/tests/factories/billing-address.js
tests/dummy/app/tests/factories/department-employment.js
tests/dummy/app/tests/factories/department.js
tests/dummy/app/tests/factories/employee.js
tests/dummy/app/tests/factories/mailing-address.js
tests/dummy/app/tests/factories/name.js
tests/unit/models/employee-test.js

As discussed in #184 I've added unit tests to test for support of https://github.com/lytics/ember-data-model-fragments. It's not comprehensive but it's a start. Acceptance tests can follow.
I've added an `employee` model which from a `model-fragment` point of view looks like:
```
Employee
* name (fragment)
* titles (array)
* departmentEmployments (fragmentArray)
DepartmentEmployment
* department (fragment)
Department
* addresses (fragmentArray)
```
As `model-fragment` supports polymorphic `fragmentArrays` I added `billing-address` and `mailing-address` as well but was unsure how to construct the list using a factory to test it.
@danielspaniel anything else you think we should test for?

Added tests for Ember Data Model Fragment factory support in unit tests

---

addon/converter/fixture-converter.js
tests/dummy/app/models/employee.js

Ember Data allows you to do: `name: DS.attr()` without specifying a type for the attribute.
In some circumstances having no type set would cause your tests to crash on the following line: https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/converter/fixture-converter.js#L32 because `this.transformKeys` was `true` but `type` was `undefined`.
```
if (!this.transformKeys || type.match('-mf')) {
return this.noTransformFn;
}
```
Adding `position: attr()` caused the [employee acceptance test](https://github.com/danielspaniel/ember-data-factory-guy/blob/master/tests/acceptance/employee-view-test.js#L10) to break. This fix makes it pass.

Fix type.match crasher

---

README.md

Added documentation for setting up Ember Data Model Fragments

Updated README with documentation about using ember-data-model-fragments

---

addon/converter/fixture-converter.js
tests/dummy/app/models/employee.js
tests/dummy/app/models/manager.js
tests/dummy/app/models/review.js
tests/dummy/app/models/salary.js
tests/dummy/app/serializers/manager.js
tests/dummy/app/tests/factories/employee.js
tests/dummy/app/tests/factories/manager.js
tests/dummy/app/tests/factories/review.js
tests/dummy/app/tests/factories/salary.js
tests/helpers/utility-methods.js
tests/unit/rest-adapter-test.js

Currently factory-guy only supports embedding records using:
```
attrs: {
reviews: {embedded: 'always'}
}
```
but Ember Data also allows you to embed records using:
```
attrs: {
reviews: {deserialize: 'records'}
}
```
From [the API docs](http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html#toc_using-embedded-records)
> The attrs option for a resource `{ embedded: 'always' }` is shorthand for: `{ serialize: 'records', deserialize: 'records' }`

Support embedding records using `deserialize: 'records'`

---

index.js

I don't know if this is the right solution but it seems like it could be. I tried to test it, but the demo app's index.html has all of it's code commented out. Why is that?

Adding factories to the app instead

---

addon/mocks/mock-create-request.js
addon/mocks/mock-request-match.js
addon/mocks/mock-update-request.js
tests/unit/shared-factory-guy-test-helper-tests.js

Here's some tests for mockUpdate().match().
The tests pass and it works how I need in my own app's tests when I copy the methods match(), extraRequestMatches(), and attributesMatch() from mock-create-request.js to mock-update-request.js.
But you probably want something cleaner than a copy/paste job. Not sure if there would be any variation  for update. If not, maybe a 'mock-match-request' class with those methods which both create and update extend.

Tests for mockUpdate.match #216

---

tests/unit/shared-factory-guy-test-helper-tests.js

```
not ok 368 PhantomJS 2.1 - DS.RESTAdapter/JSONSerializer | #mockFind: failure with fails method
---
actual: >
false
expected: >
true
stack: >
http://localhost:7357/assets/test-support.js:4147:17
exception@http://localhost:7357/assets/vendor.js:59253:9
onerrorDefault@http://localhost:7357/assets/vendor.js:51230:33
trigger@http://localhost:7357/assets/vendor.js:73618:19
http://localhost:7357/assets/vendor.js:74869:40
invoke@http://localhost:7357/assets/vendor.js:19475:20
flush@http://localhost:7357/assets/vendor.js:19539:17
flush@http://localhost:7357/assets/vendor.js:19347:22
end@http://localhost:7357/assets/vendor.js:19702:30
run@http://localhost:7357/assets/vendor.js:19824:21
join@http://localhost:7357/assets/vendor.js:19844:30
join@http://localhost:7357/assets/vendor.js:40323:33 …
```

mockFind does not return a failed response

---

README.md
addon/mocks/mock-get-request.js
addon/utils/helper-functions.js
tests/unit/shared-factory-guy-test-helper-tests.js
tests/unit/utils/helper-functions-test.js

This PR introduces new functionality to match by some params. Here's the excerpt from documentation additions:
```js
// Create list of models
let users = buildList('user', 2, 'with_hats');
let user1 = users.get(0);
mock = mockQuery('user').returns({ids: [user1.id]});
mock.withParams({name:'Bob', age: 10})
// When using 'withParams' modifier, params hash must match exactly
store.query('user', {name:'Bob', age: 10}}).then(function(models) {
// models will be one model and it will be user1
});
// The following call will not be caught by the mock
store.query('user', {name:'Bob', age: 10, hair: 'brown'}})
// 'withSomeParams' is designed to catch requests by partial match
// It has precedence over strict params matching once applied
mock.withSomeParams({name:'Bob'})
// Now both requests will be …
```

withSomeParams modifier for mockGetRequest

---

README.md
addon/mocks/mock-request.js
tests/unit/mock-request-test.js

These methods can be used to temporarily disable and re-enable the mock or to completely destroy the mockjax handler.
The excerpt from the docs:
> 
- Use method `disable()` to temporarily disable the mock. You can re-enable
the disabled mock using `enable()`.
>
- Use method `destroy()` to completely remove the mockjax handler for the mock.
The `isDestroyed` property is set to `true` when the mock is destroyed.

disable(), enable(), and destroy() methods for mocks

---

addon/mocks/mock-request.js
addon/mocks/mock-update-request.js
tests/unit/shared-factory-guy-test-helper-tests.js

This PR addresses #226 
Even though the issue is fixed, there are still questions on whether `convertErrors` should be adapter specific. For example, someone using json-api, would expect errors as per spec:
http://jsonapi.org/examples/#error-objects-multiple-errors
When with `DS.RESTAdapter` it's just `{errors: {field: ['error 1', 'error 2']}}`
Should we remove that option at all and do the conversion implicitly depending on what adapter is in use?

es6 args destructuring removed from public api on mocks

---

addon/factory-guy.js
addon/mocks/mock-get-request.js
addon/payload/base-payload.js
addon/payload/rest-payload.js

- Ember 2.8 deprecated Ember.Array.contains
- Use Ember.array.includes if available

Use Array.includes instead of deprecated contains if possible

---

README.md

Clicking the mockFindRecord link will now take you to the mockFindRecord section in the readme, which is probably what you expect to happen :)

Fix a link to mockFindRecord in the readme

---

README.md
addon/utils/load-scenarios.js
index.js

Closes: https://github.com/danielspaniel/ember-data-factory-guy/issues/254
CHANGELOG:
**Updated** index.js to support using factory-guy in other environments
**Updated** README to show configuration needed for using factory-guy in other environments
DESCRIPTION:
This PR adds support for using factory-guy in other environments to the base cases of `development` and `test`.
The user just needs to add:
```
// file: config/environment.js
ENV.factoryGuy = true;
``` 
to the environments in which factory-guy is desired.
By default, the test environment is still enabled but now a user can turn it off by specifying:
```
// file: config/environment.js
if (environment === 'test') {
ENV.factoryGuy = false;
...
}
```

Add support for using factory-guy in other environments

---

addon/converter/rest-fixture-converter.js

I have a model 'department', which is hierarchal. Each department can have a parent. So the department model has a relationship with its own model type 'department'.
In my tests, I have a trait called 'parent' and one called 'primary'.
```
FactoryGuy.define('department', {
traits: {
primary: {
name: 'Primary Department',
parent: FactoryGuy.belongsTo('department', 'parent'),
},
parent: {
name: 'Parent Department',
parent: null
}
}
//...
});
```
When I use `buildList()` and include the 'primary' trait, the result I get back contains only the 'parent' model.
Stepping through, I found this is because addIncludedArray() in rest-fixture-converter is setting `payload[key] = this.included[key];`. Since the key 'department' is present in 'included', it replaces everything that in the payload when …

addIncludedArray() replacing payload data with included

---

README.md
addon/mocks/attribute-matcher.js
tests/unit/shared-factory-guy-test-helper-tests.js

**tl;dr** Allow `match` to accept a function or attribute(s) to determine whether a create or update matched.
The function passed to `match` is given the `requestData` and can perform bespoke logic to determine whether a request matched or not. If the function returns `true` then a match is recorded, otherwise it is not.
We have a use-case where we're updating a complex, nested model called `Parent`. `Parent` hasMany `Child` relationships, each of which has multiple attributes. We're mocking an update to `Parent` but what we really care about is one change to an attribute of `Child`, let's say `description`. Using the existing `match` function we would need to pass in the entire child structure, which is quite unwieldy. By allowing `match` to receive a function the responsibility of …

Allow mockCreate/mockUpdate to receive a matching function

---

README.md
addon/builder/fixture-builder.js
addon/converter/fixture-converter.js
addon/converter/jsonapi-fixture-converter.js
addon/converter/rest-fixture-converter.js
addon/mocks/exposed-request-functions.js
addon/mocks/mock-create-request.js
addon/mocks/mock-get-request.js
addon/model-definition.js
addon/utils/manual-setup.js
tests/dummy/app/tests/factories/cat.js
tests/helpers/utility-methods.js
tests/unit/drf-adapter-test.js
tests/unit/factory-guy-test.js
tests/unit/models/profile-test.js
tests/unit/models/user-test.js
tests/unit/shared-factory-guy-test-helper-tests.js
tests/unit/utils/helper-functions-test.js

Came across a couple of typos in the Readme and decided to run a spell check. Hope you don't mind and I'm not being too pedantic ;-)

Misc. typo fixes

---

addon/model-definition.js
tests/unit/factory-guy-test.js
tests/unit/mock-request-test.js

We kinda discussed using assertions rather than warnings for missing traits in [another PR](https://github.com/danielspaniel/ember-data-factory-guy/pull/264#issuecomment-266524766). I decided to spike this out. 
If this is merged it might be worth flagging this - maybe this change is bigger than a patch release. It's possible it will cause test failures for people where before they were seeing (but perhaps not noticing or acting on) warnings that were there all along.

Use assert rather than warn for missing traits

---

addon/builder/fixture-builder-factory.js

DjangoSerializer was not being imported when require for `ActiveModelSerializer` failed. I moved them into separate try/catch blocks.

Fix DjangoSerializer import

---

package.json

I noticed the package.json doesn't mirror the release number

Update package.json to be the correct release number

---

README.md
addon/converter/active-model-fixture-converter.js
addon/mocks/exposed-request-functions.js
addon/mocks/mock-request.js
config/environment.js
tests/acceptance/user-view-test.js
tests/dummy/app/transforms/just-a-string.js
tests/helpers/utility-methods.js
tests/unit/mock-request-test.js

Work in Progress
- Shortening the table of contents
- Putting the "defining factories" stuff together, and before the "using factories" stuff
- Using relative links for the cross-linking (better experience for forks)
- Moved the changelog to the bottom
- Moved the "how this works" nearer the top
- Small tidy-ups and tweaks to the code snippets
- Misc tweaks to other code.
I feel like this could use more eyes :-)
More context from earlier discussions over at https://github.com/lorcan/ember-data-factory-guy/pull/1

Some tweaks to the README

---

index.js

Currently the build fails as `included` and `treeFor` hooks might be called in different contexts.
`included` hook is being run in `_notifyAddonIncluded` - https://github.com/ember-cli/ember-cli/blob/8637a9ab4a189cd375b309c44a66bdc6513f3bb2/lib/broccoli/ember-app.js#L508 and `treeFor` would be called in `addonTreeFor` - https://github.com/ember-cli/ember-cli/blob/8637a9ab4a189cd375b309c44a66bdc6513f3bb2/lib/broccoli/ember-app.js#L535.
The addon that has `ember-data-factory-guy` as its dependency would run default `ember-cli` `treeFor` implementation which would in turn call `eachAddonInvoke` - https://github.com/ember-cli/ember-cli/blob/8637a9ab4a189cd375b309c44a66bdc6513f3bb2/lib/models/addon.js#L462 to iterate over its own addons. 
For those addons the context would be different from …

fix build if ember-data-factory-guy used for tests inside addon

---

package.json

As of Ember 2.12 the addon started triggering the following deprecation warning:
```
DEPRECATION: Addon files were detected in `.../node_modules/ember-data-factory-guy/addon`, but no JavaScript preprocessors were found for `ember-data-factory-guy`.
Please make sure to add a preprocessor (most likely `ember-cli-babel`) to in `dependencies` (NOT `devDependencies`) in `ember-data-factory-guy`'s `package.json`.
```

Silence JavaScript preprocessor deprecation warning on Ember 2.12

---

README.md

The overloading of the `find` method was [deprecated in ember-data v1.13](https://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html). This PR updates the README to reflect this, replacing references to `store.find` for single object lookups with `store.findRecord` 🙂

Update `find` => `findRecord` in README

---

tests/dummy/app/models/cool-stoner.js
tests/unit/factory-guy-test.js

I think I've found a situation where the inheritance doesn't work as expected.
Basically when we use more than one level, it doesn't seem to work. In the test, the overridden property is undefined. It also seems to happen with properties that are defined in the parent factories (they end up being undefined as well).

add failing test for factory inheritance

---

index.js

In upgrading to Ember 2.16.1 and Ember-Data 2.16.3 I now get the following error when I try to launch `error s` unless I remove the reference to pretender-shim.js.  Note that it was removed from ember-cli-pretender 10 months ago: https://github.com/rwjblue/ember-cli-pretender/commit/f25275e5e736387e1570b0b5ba99ac8c70d79e6e.
```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open 'appDirectory/tmp/source_map_concat-input_base_path-wUctF9pK.tmp/vendor/pretender-shim.js'
at Object.fs.openSync (fs.js:648:18)
at Object.fs.readFileSync (fs.js:553:33)
at SourceMap.addFile (appDirectory/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
at appDirectory/node_modules/broccoli-concat/concat.js:200:16
at …
```

Remove reference to pretender-shim.js

---

addon/converter/rest-fixture-converter.js

This is to address a deprecation warning:
```
DEPRECATION: Ember.String.pluralize() is deprecated. Please explicitly: import { pluralize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]
```

Import pluralize from ember-inflector

---

package.json

Otherwise, the using application will break with a ReferenceError
```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (addons)] failed with:
ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "modules/ember-data-factory-guy/builder"
at /Users/paul/Projects/ted/node_modules/ember-data-factory-guy/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
at Array.map (native)
...
```

[BUGFIX] transform-object-rest-spread plugin must be a dependency

---

README.md
tests/acceptance/employee-view-test.js
tests/dummy/app/serializers/name.js

I suggest a couple of small changes to documentation to make it easier to understand that mixing `build` and `make` can have unpredictable results. I also underline that serializers are taken into consideration in `build` methods (what might be obvious, but I feel that it is easy to forget about).
Also small clean up in acceptance tests regarding model fragments.

Propose changes to documentation

---

addon/utils/helper-functions.js

Without this change our tests are running into errors like described in https://github.com/emberjs/ember.js/issues/16049, because computed properties are included in the for-in loop and the nested `mergeDeep()` call will try to clone `isDescriptor` and other internal properties of the computed property.
Related to https://github.com/danielspaniel/ember-data-factory-guy/issues/328
/cc @danielspaniel

mergeDeep: Add `hasOwnProperty()` check

---

addon/converter/fixture-converter.js
tests/dummy/app/models/comic-book.js
tests/dummy/app/tests/factories/comic-book.js
tests/helpers/utility-methods.js
tests/unit/active-model-adapter-test.js
tests/unit/json-adapter-test.js
tests/unit/rest-adapter-test.js

It seems that at the moment there is only test coverage for embedded, polymorphic hasMany relationships - but not for non-polymorphic ones.
Non-polymorphic embedded hasMany works for rest and json serializer, but it doesn't with the ActiveModelSerializer.
The fix basically includes 3 changes in the codebase, which hopefully are comprehensible. I will add some comments for further explanation.
Happy to update this PR, split it up so it only contains the fix (and add test coverage in a separate PR). Also, let me know if there is something I've missed, but testing wise the fixes seem not to influence other parts, even though the 3 changes look more substantial...

Non-polymorphic embedded hasMany works with AMS

---

addon/factory-guy.js

I was having an issue where doing lots of `makeList` in a test caused more than 10 runloops to be created which caused an infinite rendering invalidation error.
A similar issue was reported here
https://github.com/ember-redux/ember-redux/issues/64#issuecomment-267053666
And fixed here using `run.join` to only create new loops as needed
https://github.com/ember-redux/ember-redux/pull/69

Use run.join instead of run

---

addon/factory-guy.js
tests/unit/factory-guy-test.js

Currently if you use `FactoryGuy#make` to generate a `ModelFragment` it returns a json hash of the properties of the fragment. In keeping with the consistency of using `Factory#make` for a regular Ember Data record, I think it should return an actual model instance instead, in this case a `ModelFragment`.

Allow `make` to return an instance of `ModelFragment`

---

addon/factory-guy.js

After pulling the latest version with [my fragment fix](https://github.com/danielspaniel/ember-data-factory-guy/pull/362) into my app we started getting asynchronous errors when creating fragments directly using `make`. I've updated to create the fragment inside a run loop. This is similar to what we do when pushing records into the regular store just below these lines.
``` js
model = join(() => this.store.push(data));
```

Create fragment inside a run loop

---

package.json
yarn.lock

This avoids adding old 7.0 versions along with 7.2 newer ones

change babel dependency to ^7.0.0 to allow for future 7.x.x releases

---

addon/mocks/exposed-request-functions.js
addon/mocks/mock-delete-request.js
tests/unit/mocks/mock-delete-test.js

In regards to https://github.com/danielspaniel/ember-data-factory-guy/issues/374, we found a simpler workaround for the time being to have mockDelete support passing the model as record in the snapshot (since DS.Snapshot also passes this value), which we can utilize instead of `snapshot.attr` in our case. This was simpler than trying to mimic all functionality of DS.Snapshot (which is in -private namespace). 
This is what `mockUpdate` does as well and since `mockDelete` is generally dealing with a persisted record in the same way as `mockUpdate` they should behave the same in regards to generating a fake snapshot.
I simply copied over the `makeFakeSnapshot` method from `mock-update-request.js`. I don't know if there is a better way. I thought about a mixin like `AttributeMatcher` or …

mockDelete should also add model to fake snapshot

---

addon/mocks/attribute-matcher.js
tests/unit/shared-adapter-behaviour.js

Fixes https://github.com/danielspaniel/ember-data-factory-guy/issues/379 by relaxing the assumption that `requestBody` is always a stringified JSON object. In the cases where it isn't, we can leave it untouched and pass it down to the matcher function so that it determines what to do.

Tolerate non-string request bodies

---

addon/mocks/mock-any-request.js
tests/unit/mocks/mock-any-test.js

Fixes https://github.com/danielspaniel/ember-data-factory-guy/issues/381
Allows you to use `withSomeParams` with `mock`

Fix mock#withSomeParams issue

---

package.json
yarn.lock

This PR upgrades Pretender to v3 (while allowing previous versions >=2.1.1).

Upgrade pretender to v3

---

addon/converter/fixture-converter.js
tests/dummy/app/models/dog.js
tests/dummy/app/tests/factories/dog.js
tests/helpers/utility-methods.js
tests/unit/active-model-adapter-test.js

This fixes https://github.com/danielspaniel/ember-data-factory-guy/issues/393
Not sure if I need to keep the `parentType` property there.
Could also do with adding another test for a serializer which includes a custom relationship key.

Fix relationship key transformation

---

addon/mocks/mock-any-request.js
addon/utils/helper-functions.js
tests/helpers/utility-methods.js
tests/unit/mocks/mock-any-test.js
tests/unit/mocks/mock-request-test.js

A `MockAnyRequest` currently won't correctly match requests when the `.withParams` method is used with array parameters.

Fix .withParams for array parameters

---

addon/mocks/mock-delete-request.js
addon/mocks/mock-get-request.js
addon/mocks/mock-store-request.js
addon/mocks/mock-update-request.js
tests/unit/mocks/mock-find-record-test.js
tests/unit/mocks/mock-request-test.js

Related issue: https://github.com/danielspaniel/ember-data-factory-guy/issues/409
Problem:
While developing one of the tests in my app it turned out that when creating mocked find operation from already mocked model, like:
```
const user = make('user');
mockFindRecord(user);
```
the Snapshot object never had the `record` set to this model.

Fix snapshot record for Get requests

---

README.md

I searched the repo for `data url` trying to find how to ignore them. The search turned up nothing so adding this to the readme could save someone time in the future.
Awesome that this is possible : )

Highlight ability to use pretender's passthrough feature

---

addon/factory-guy.js
tests/unit/mocks/mock-query-record-test.js

Clones the query params before handing off to the adapter in case the adapter modifies it

fix error when adapter modifies queryParams

---

index.js

Setting this to true causes the Ember process to watch the addon directories for changes and live reload when something changes ([documentation](https://ember-cli.com/api/classes/Addon.html#method_isDevelopingAddon)). We generally don't want to live reload when something in `node_modules` changes unless we are actively working on it and with a polling watcher this can be CPU intensive. Based on [the commit where it was introduced](https://github.com/danielspaniel/ember-data-factory-guy/commit/7b57d0daa600ffa783bfb5859e9d74a1e0a90375), which appears to be unrelated, I think introducing this may have been unintentional.

Set `isDevelopingAddOn = false`

---

CHANGELOG.md
README.md
package.json

Part of https://github.com/danielspaniel/ember-data-factory-guy/issues/419
Starts the process of changing repo ownership over to the adopted-ember-addons org.
* Changes all references of www.github.com/danielspaniel to www.github.com/adopted-ember-addons
* Documents the release process. (I know adopted-ember-addons has an official process based on using release-it but I don't think we need to figure that out right now to change ownership)

Change ownership to adopted-ember-addons

---

package.json
yarn.lock

See https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/427

Bump pretender to 3.4.3

---

.github/workflows/ci.yml

Until we support ember-auto-import v2 we need to allow `ember-release` and `ember-beta` to fail so CI runs

Allow ember-release and ember-beta to fail

---

addon/factory-guy.js
addon/index.js
addon/mocks/exposed-request-functions.js
addon/scenario.js

Part of https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/444
Remove the following deprecated helpers for the next major release
* `mockSetup` & `mockTeardown` which are replaced by using `setupFactoryGuy`
* `mockFind` which is superseded by `mockFindRecord`

Remove deprecated helpers

---

CHANGELOG.md
README.md
RELEASE.md
package.json
yarn.lock

Part of #444 
Adopted Ember Addon org guidelines are that repos should [automate their release process using release-it](https://github.com/adopted-ember-addons/program-guidelines#release-process).
* Adds `release-it` and `release-it-lerna-changelog` as `devDependencies`
* Adds `RELEASE.md` with release process information, automated from [`create-rwjblue-release-it-setup`](https://github.com/rwjblue/create-rwjblue-release-it-setup)
* Updates `CHANGELOG.md` with a bunch of missing releases.

Add release-it to repo and generate initial CHANGELOG.md

---

addon/utils/helper-functions.js

We have a very large Ember application with loads of modules, so the `requireFiles` function takes a long time.
This is because the `fileSeen` array is very long, but only a very small subset of these match the `filePattern` regex.
The `filePattern` regex is very simple, but the `excludeRegex` is more complex. So if we evaluate the simple one first, we'll only have to evaluate the more complex one a much smaller number of times.
I also took the opportunity to simplify the `excludeRegex` since it's the file extension that we really care about - at the end of the path.
Time spent in `requireFiles` for one test module of our app before the change was 2605ms, time spent after the change was 70ms.

Make requireFiles do less work for larger applications

---

addon/converter/fixture-converter.js

using factory guy without model-fragments results in errors (at least on ember 4.4). this should fix this.

fix: remove hard dependency on model-fragments

---

package.json
yarn.lock

This PR is helping out the efforts for ember v4 https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/444
active-model-adapter 2 depends on ember-cli-babel 6 while also using EAI, [which is a blocker to ember-auto-import v2](https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md#drop-babel-6)
active-model-adapter 3 does not have that issue.
active-model-adapter 4 is also available, but it requires ember-auto-import v2
So active-model-adapter 3 is a nice middle ground for now, until this addon is on EAI2
---
Bumps ember-maybe-import-regenerator to v1 - one less dependency on ember-cli-babel 6
---
We might want to consider bumping to ember-data 3.25 - it updates ember-inflector so is one less thing using ember-cli-babel 6, and still works with …

chore: update active-model-adapter to 3.0.1

---

addon/factory-guy.js
addon/mocks/mock-create-request.js
addon/mocks/mock-get-request.js
addon/mocks/mock-request.js
addon/mocks/mock-update-request.js
addon/model-definition.js
addon/payload/base-payload.js
addon/payload/drf-payload.js
addon/payload/json-api-payload.js
addon/utils/helper-functions.js

Address deprecation warnings. (See https://github.com/emberjs/rfcs/blob/master/text/0750-deprecate-ember-assign.md)
Fix https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/479
Part of the quest towards a v4 release: https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/444
Replaces `assign` from `@ember/polyfills` with javascript built-in `Object.assign`.
NOTE that Object.assign is not available in IE11, so this commit removes some IE11 support.

Replace polyfill assign with Object.assign

---

addon/builder/fixture-builder-factory.js
addon/converter/fixture-converter.js
addon/factory-guy.js
package.json
yarn.lock

This PR removes the use of `require` as a means of deciding whether to import a package or not and replaces with the the @embroider/macros provided `dependencySatisfies` and `importSync`. These functions are backwards compatible and therefore will work in both Classic and Embroider builds.

Replace `require` with `importSync` to play nice with Embroider

---

addon/converter/active-model-fixture-converter.js
addon/converter/fixture-converter.js

This change should fix compatibility with ember-data 4.13 and maybe 5.x
Chatted w/ @runspired about this and `key` was a duplicate undocumented property which was removed from these newer versions.
It unfortunately seems quite a bit of effort to add these newer ember-data's to the test-matrix since the tests rely on e.g. model-fragments which are not supported.

Swap relationship.key for relationship.name to fix support w/ ember-data 4.13+

---

package.json
pnpm-lock.yaml

This addon uses `@ember/string` in a few places, which is no longer included as part of Ember in later versions. Need it listed in peer deps if using in modern projects/builds with stricter dependency management

chore: add `@ember/string` peerDependency

---

README.md
test-app/config/environment.js

I'm being overly verbose here to make sure no-one is confused or left behind.
Realistically, the only changes needed are to add some deps, and import the factories.

docs: add upgrade docs for v5

---

addon/package.json
package.json
test-app/package.json

Noticed that the "Release Notes" of renovate PRs for bumps for this addon are blank.
Hoping this rectifies that

chore: add repository keys to package.json to help release changelogs

---

addon/src/factory-guy.js
test-app/ember-cli-build.js
test-app/tests/test-helper.js
test-app/tests/unit/mocks/mock-find-all-test.js
test-app/tests/unit/mocks/mock-find-record-test.js
test-app/tests/unit/shared-adapter-behaviour.js

Resolves https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/493
Ensures we don't expect `store.willDestroy()` to exist, as Store is not an EmberObject in upcoming versions of ember-data. This deals with the deprecation, and have configured the test-app to error if it tries to do so.
I also configured the tests to have better test isolation, and dealt with violations of that.

refactor: deal with using Store EmberObject function deprecations

---

addon/package.json
addon/src/converter/fixture-converter.js
package.json
pnpm-lock.yaml
test-app/app/services/store.js
test-app/package.json
test-app/tests/unit/models/employee-test.js

Added support for the latest EDMF version in case anyone was stuck on v5, so that they can get recent updates.
Likely to drop it in next major in favour of updating to later versions of ember-source + ember-data that EDMF does not support. We'll be supporting ember-data versions that has fragment-like features built-in.

feat: support ember-data-model-fragments v6

---

.npmrc
pnpm-lock.yaml
pnpm-workspace.yaml
test-app/config/ember-try.js
test-app/package.json

Noticed that we don't even need ember-source-channel-url, it seems other repos get away without it just fine, eg https://github.com/ember-modifier/ember-modifier/pull/950

chore: improve pnpm config, fix ember-release try scenario

---

test-app/ember-cli-build.js

pretender is still the default for the addon, but we can run the baseline tests against msw, to gain the performance benefit and to ensure we treat MSW as the desired option going forward.
Note: we still have ember-try scenarios for both msw and pretender, which each run the whole test suite. This just sets msw as the library to use for all the other try scenarios and the baseline tests.
In case you're wondering the difference in perf, we can see these line items from the github actions for the different scenarios;
MSW - 34s
Pretender - 1m 1s

test: use msw for baseline addon tests, much faster.

---

addon/src/scenario.js
docs/request-manager.md
docs/upgrading.md

allows for `this.requestManager` to be accessed in a scenario, as long as `run()` has been called
```ts
class MyScenario extends Scenario {
run() {
super.run()
this.mock(...)
this.requestManager.pretender.get(...)
}
}
```

fix: set request manager in scenario
