adopted-ember-addons/ember-data-factory-guy

README.md

Removed extra right curly brace

Mocking a failed reload typo fix

---

addon/mock-create-request.js
tests/unit/factory-guy-test-helper-test.js

Lemme know what you think.
Much of the conversation that led up to this pull request is here: https://github.com/danielspaniel/ember-data-factory-guy/pull/96

handleCreate now respects user-set id in andReturn

---

README.md

This is an exceptional addon, so it would be nice that GitHub users could see the quality score. Absolutely feel free to take or leave this PR. My feelings won't be hurt!

Updates README.md to include Ember Observer Score

---

README.md

surfacing useful info from https://github.com/danielspaniel/ember-data-factory-guy/issues/94#issuecomment-112493918

add note to avoid using ember-data-1.0.0-beta.19.2

---

README.md
tests/acceptance/users-delete-test.js
tests/dummy/app/components/user-list.js
tests/dummy/app/templates/components/user-list.hbs

and added test case demonstrating using handleFindAll and handleDelete.  This would close #128.

update README for handleFindAll

---

README.md

Super critical fix

---

index.js

Production build does not include factory guy

---

README.md

Added video to your introduction

---

bower.json

I think the title speaks for itself!

Update jquery-mockjax to 2.1.1

---

index.js

Otherwise ember-data-factory guy ends up in vendor.js

Add 'addon' guard to treeFor method

---

README.md

I believe there are some dialects of English that use 'you' as a  2nd-person possessive pronoun, but... 😉

minor syntax fix

---

addon/utils/load-scenarios.js
addon/utils/manual-setup.js

This allows us to use this addon with the changes coming in https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md
Resolves emberjs/ember-test-helpers#230
/cc @danielspaniel @rwjblue

Allow passing "owner" into manualSetup()

---

addon/factory-guy.js
addon/mocks/mock-create-request.js
addon/mocks/mock-request.js
addon/mocks/mock-update-request.js
addon/model-definition.js
addon/payload/base-payload.js
addon/payload/drf-payload.js
addon/utils/helper-functions.js

This would help people who are still stuck with Phantomjs.

Use assign from ember polyfills

---

README.md
addon/mocks/attribute-matcher.js
tests/acceptance/user-view-test.js
tests/unit/shared-adapter-behaviour.js

Pass the requestBody as it is to user supplied matching function

---

package-lock.json
package.json
yarn.lock

This PR will fix pretender issue.
#353 #352

Fix pretender

---

.travis.yml

Use yarn and Travis provided version of Chrome

---

tests/unit/mocks/mock-any-test.js

@danielspaniel after our discussions on Discord I added some tests which verified some `mock` behaviour to me. No harm in adding them to the test suite.

Add some additional tests for `mock`

---

README.md

Otherwise it's not immediately obvious where this utility is imported from.

add import statement for `setupFactoryGuy`

---

addon/converter/fixture-converter.js
tests/dummy/app/models/rod.js
tests/dummy/app/tests/factories/rod.js
tests/dummy/app/transforms/element.js
tests/unit/converter/fixture-converter-test.js

Fixes https://github.com/danielspaniel/ember-data-factory-guy/issues/377

Pass options to transforms

---

package.json
yarn.lock

Solves https://github.com/danielspaniel/ember-data-factory-guy/issues/387

Update pretender version

---

addon/mocks/mock-any-request.js
tests/unit/mocks/mock-any-test.js

This fixes https://github.com/danielspaniel/ember-data-factory-guy/issues/396

Fix withSomeParams for GET requests

---

README.md
addon/mocks/exposed-request-functions.js
addon/mocks/mock-any-request.js
tests/unit/mocks/mock-any-test.js

Fix issue setting mock status not working.

---

package.json
pnpm-lock.yaml

Closes https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/488

update ember-auto-import to v2

---

.github/workflows/ci.yml
config/ember-try.js
package.json
pnpm-lock.yaml

Resolves https://github.com/adopted-ember-addons/ember-data-factory-guy/pull/492

chore: ember-inflector added to peerDeps

---

package.json
pnpm-lock.yaml

Hopefully this fixes releasing again.

chore: fix root devDeps for release-plan

---

addon/package.json
addon/src/mocks/attribute-matcher.js
addon/src/mocks/exposed-request-functions.js
addon/src/mocks/mock-create-request.js
addon/src/mocks/mock-get-request.js
addon/src/mocks/mock-links-request.js
addon/src/model-definition.js
addon/src/own-config.js
docs/quick-start.md
pnpm-lock.yaml
test-app/ember-cli-build.js
test-app/tests/unit/active-model-adapter-test.js
test-app/tests/unit/converter/fixture-converter-test.js
test-app/tests/unit/factory-guy-test.js
test-app/tests/unit/json-adapter-test.js
test-app/tests/unit/jsonapi-adapter-test.js
test-app/tests/unit/mocks/mock-create-test.js
test-app/tests/unit/mocks/mock-find-all-test.js
test-app/tests/unit/mocks/mock-find-record-test.js
test-app/tests/unit/mocks/mock-request-test.js
test-app/tests/unit/mocks/mock-update-test.js
test-app/tests/unit/rest-adapter-test.js
test-app/tests/unit/shared-adapter-behaviour.js
test-app/tests/unit/shared-factory-guy-behaviour.js

Resolves https://github.com/adopted-ember-addons/ember-data-factory-guy/issues/485

feat: added useStringIdsOnly config option to avoid deprecated behaviour
